redirect sourcefolders/inject source/dynamic sources
pik-piam/madrat pull request #201
Opened 2024-01-22 14:30 UTC by pascal-sauer

2024-02-15 15:35 UTC, pascal-sauer commented
I accidentally pushed the numeric_version clarifications to this PR, but it's really just minor changes ([a075200](https://github.com/pik-piam/madrat/pull/201/commits/a0752009d9003d1584fd78b1a1a8d18727506be6)), so it should be fine

2024-02-23 22:27 UTC, tscheypidi requested changes

2024-02-23 22:27 UTC, tscheypidi commented on R/getLinkFunction.R
> +getLinkFunction <- function() {
please add a documentation

2024-02-23 22:27 UTC, tscheypidi commented on R/redirectSource.R
> +#' @export
I find that confusing to have two rather similar functions exported (redirect and redirectSource). Lets have a discussion whether we can unify them somehow.

2024-05-04 16:24 UTC, tscheypidi approved these changes
looks good

2024-05-06 09:34 UTC, merged