Optional filename tag for retrieveData
pik-piam/madrat pull request #51
Opened 2021-05-04 13:12 UTC by pfuehrlich-pik

I applied some auto-formatting, so if actual changes are hard to see only look at commits after the initial formatting.
fullXYZ functions may now `return(list(tag = "mytag"))`, which will result in a filename like rev0_h12_test_mytag.tgz (with mytag as suffix)

2021-05-04 13:54 UTC, k4rst3ns commented
I am unsure, is there still a hash in the tgz-file name summarizing the settings of the full*-function call?
so that something like rev0_h12_test_mytag_<hash_including_all_parameters_of_full*_call>.tgz
I would be happy to get an info about what the name includes at the moment and what the changes introduces at the example of the fullCELLULARMAGPIE from mrmagpie.

2021-05-04 15:49 UTC, pfuehrlich-pik commented
Yes the argument hash is still there. It is omitted if no arguments are passed to the fullXYZ method, that's why it is missing in my example. The file name is the same as before, here is the code where it is assembled:
```
collectionname <- paste0(
    "rev", rev, dev, "_", regionscode, "_", argsHash, tolower(model),
    ifelse(getConfig("debug") == TRUE, "_debug", "")
  )
```
With this PR a tag is appended to the end of the filename (but before .tgz) if the fullXYZ method ends with `return(list(tag="mytag"))`. Here's the corresponding code:
```
    collectionname <- paste0(collectionname,
                             ifelse(is.list(returnedValue) && exists("tag", returnedValue),
                                    paste0("_", returnedValue$tag),
                                    ""))
```
So we have a filename like rev0_h12_test_1234567_mytag.tgz, where 1234567 is the argsHash.
For fullCELLULARMAGPIE nothing will change, unless it returns list(tag = "anything").

2021-05-04 16:28 UTC, pfuehrlich-pik commented
The tag is not used in the cachefolder name. However, caching is not applied to fullXYZ functions, but rather to the calc functions called from fullXYZ. These are cached as before, the tag does not show up here, but the cache files are still valid when running the fullXYZ again with a different tag.

2021-05-06 10:01 UTC, k4rst3ns approved these changes
From user side no issue just praise for these changes.

2021-05-06 12:02 UTC, tscheypidi requested changes

2021-05-06 12:02 UTC, tscheypidi commented on R/retrieveData.R
> +    warning(paste0("At least one of the regex characters [](){}*+?|^$.\\ appeared in collectionname",
can you add a test which triggers this new warning?

2021-05-07 11:09 UTC, tscheypidi approved these changes

2021-05-07 11:16 UTC, merged